apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-go
  namespace: ci
  labels:
    app: back
spec:
  replicas: 3
  selector:
    matchLabels:
      app: back
  template:
    metadata:
      labels:
        app: back
    spec:
      containers:
        - name: container-back
          image: qcharlies/backend-go:2.0
---
apiVersion: v1
kind: Service
metadata:
  name: backend-go
  namespace: ci
  labels:
    app: back
spec:
  selector:
    app: back
  ports:
    - name: default
      protocol: TCP
      port: 80
      targetPort: 9090