apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-port
  labels:
    app: back
spec:
  replicas: 3
  selector:
    matchLabels:
      app: back
  template:
    metadata:
      labels:
        app: back
    spec:
      containers:
      - name: container1
        image: nginx:alpine
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: service-port
  labels:
    app: back
spec:
  type: NodePort
  selector:
    app: back
  ports:
    - name: default
      protocol: TCP
      port: 8080
      targetPort: 80