apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
  labels:
    app: front
spec:
  replicas: 3
  selector:
    matchLabels:
      app: front
  template:
    metadata:
      labels:
        app: front
    spec:
      containers:
      - name: container1
        image: nginx:alpine
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: my-service
  labels:
    app: front
spec:
  selector:
    app: front
  ports:
    - name: default
      protocol: TCP
      port: 8080
      targetPort: 80