apiVersion: v1
kind: Pod
metadata:
  name: pod2
  labels:
    app: back-end
    env: dev
spec:
  containers:
  - name: container1
    image: python:3.6-alpine
    command: ['sh', '-c', 'echo cont1 > index.html && python -m http.server 8082']
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
  - name: container2
    image: python:3.6-alpine
    command: ['sh', '-c', 'echo cont2 > index.html && python -m http.server 8083']
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
