apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: test-replicaset
  labels:
    app: test
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: container
        image: nginx:alpine
        ports:
        - containerPort: 80