apiVersion: v1
kind: Secret
metadata:
  name: mysecret-env
type: Opaque
stringData:
  username: $USER
  password: $PASSWORD
---
apiVersion: v1
kind: Pod
metadata:
  name: mypod
spec:
  containers:
  - name: mypod
    image: nginx:alpine
    resources:
      limits:
        memory: 500M
        cpu: "500m"
      requests:
        memory: 400M
        cpu: "300m"
    volumeMounts:
    - name: secret
      mountPath: "/opt"
      readOnly: true
  volumes:
  - name: secret
    secret:
      secretName: mysecret-env
      items:
      - key: username
        path: username.txt